import type { Medication } from '../model';

/**
 * Medicamentos de exemplo para usar como fallback quando a API estiver offline
 * Estes dados garantem que o app continue funcional mesmo sem conexão
 */
export const FALLBACK_MEDICATIONS: Medication[] = [
  {
    id: 'fallback-1',
    userId: 'offline-user',
    name: 'Paracetamol',
    dosage: '500',
    dosageUnit: 'mg',
    form: 'tablet',
    purpose: 'Alívio de dores e febre',
    frequency: '8/8h',
    startDate: new Date('2025-01-01'),
    notes: 'Tomar após as refeições',
    colorCode: '#3B82F6',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-2',
    userId: 'offline-user',
    name: 'Ibuprofeno',
    dosage: '400',
    dosageUnit: 'mg',
    form: 'tablet',
    purpose: 'Anti-inflamatório e analgésico',
    frequency: '12/12h',
    startDate: new Date('2025-01-01'),
    notes: 'Não tomar de estômago vazio',
    colorCode: '#EF4444',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-3',
    userId: 'offline-user',
    name: 'Omeprazol',
    dosage: '20',
    dosageUnit: 'mg',
    form: 'capsule',
    purpose: 'Protetor gástrico',
    frequency: '1x ao dia',
    startDate: new Date('2025-01-01'),
    notes: 'Tomar em jejum, 30 min antes do café',
    colorCode: '#10B981',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-4',
    userId: 'offline-user',
    name: 'Dipirona',
    dosage: '500',
    dosageUnit: 'mg',
    form: 'tablet',
    purpose: 'Analgésico e antitérmico',
    frequency: '6/6h',
    startDate: new Date('2025-01-01'),
    notes: 'Pode causar sonolência',
    colorCode: '#F59E0B',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-5',
    userId: 'offline-user',
    name: 'Losartana',
    dosage: '50',
    dosageUnit: 'mg',
    form: 'tablet',
    purpose: 'Controle de pressão arterial',
    frequency: '1x ao dia',
    startDate: new Date('2025-01-01'),
    notes: 'Tomar sempre no mesmo horário',
    colorCode: '#8B5CF6',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-6',
    userId: 'offline-user',
    name: 'Loratadina',
    dosage: '10',
    dosageUnit: 'mg',
    form: 'tablet',
    purpose: 'Antialérgico',
    frequency: '1x ao dia',
    startDate: new Date('2025-01-01'),
    notes: 'Preferencialmente à noite',
    colorCode: '#06B6D4',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-7',
    userId: 'offline-user',
    name: 'Vitamina D3',
    dosage: '2000',
    dosageUnit: 'unit',
    form: 'capsule',
    purpose: 'Suplementação vitamínica',
    frequency: '1x ao dia',
    startDate: new Date('2025-01-01'),
    notes: 'Tomar após refeição com gordura',
    colorCode: '#FCD34D',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'fallback-8',
    userId: 'offline-user',
    name: 'Xarope Expectorante',
    dosage: '10',
    dosageUnit: 'ml',
    form: 'syrup',
    purpose: 'Tratamento de tosse',
    frequency: '3x ao dia',
    startDate: new Date('2025-01-01'),
    notes: 'Tomar com água',
    colorCode: '#14B8A6',
    icon: 'pill',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
];

/**
 * Retorna uma cópia dos medicamentos de fallback
 * Isso evita mutações acidentais dos dados originais
 */
export function getFallbackMedications(): Medication[] {
  return FALLBACK_MEDICATIONS.map(med => ({ ...med }));
}
