import type { Medication } from '../model';
import type { IMedicationRepository } from './MedicationRepository';

/**
 * Implementação Mock - útil para desenvolvimento e testes
 * ATUALIZADO com novos campos do schema SQL
 */
export class MockMedicationRepository implements IMedicationRepository {
  private medications: Medication[] = [
    {
      id: '1',
      userId: '1', // Mock user
      name: 'Paracetamol',
      dosage: '500',
      dosageUnit: 'mg',
      form: 'tablet',
      purpose: 'Alívio de dor e febre',
      frequency: '8/8h',
      startDate: new Date('2024-12-01'),
      notes: 'Tomar com água',
      colorCode: '#3B82F6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date('2024-12-01'),
      updatedAt: new Date(),
    },
    {
      id: '2',
      userId: '1',
      name: 'Ibuprofeno',
      dosage: '400',
      dosageUnit: 'mg',
      form: 'tablet',
      purpose: 'Anti-inflamatório',
      frequency: '12/12h',
      startDate: new Date('2024-12-05'),
      endDate: new Date('2024-12-15'),
      notes: 'Após as refeições',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date('2024-12-05'),
      updatedAt: new Date(),
    },
    {
      id: '3',
      userId: '1',
      name: 'Amoxicilina',
      dosage: '250',
      dosageUnit: 'mg',
      form: 'capsule',
      purpose: 'Antibiótico',
      frequency: '8/8h',
      startDate: new Date('2024-11-20'),
      endDate: new Date('2024-11-30'),
      notes: 'Completar o ciclo',
      colorCode: '#F59E0B',
      icon: 'pill',
      isActive: false,
      createdAt: new Date('2024-11-20'),
      updatedAt: new Date(),
    },
    {
      id: '4',
      userId: '1',
      name: 'Losartana',
      dosage: '50',
      dosageUnit: 'mg',
      form: 'tablet',
      purpose: 'Controle de pressão arterial',
      frequency: '24/24h',
      startDate: new Date('2024-01-01'),
      notes: 'Uso contínuo',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: '5',
      userId: '1',
      name: 'Metformina',
      dosage: '850',
      dosageUnit: 'mg',
      form: 'tablet',
      purpose: 'Controle glicêmico',
      frequency: '12/12h',
      startDate: new Date('2024-01-01'),
      notes: 'Tomar durante as refeições',
      colorCode: '#8B5CF6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: '6',
      userId: '1',
      name: 'Omeprazol',
      dosage: '20',
      dosageUnit: 'mg',
      form: 'capsule',
      frequency: '24/24h',
      startDate: new Date('2024-06-01'),
      notes: 'Em jejum, 30min antes do café',
      colorCode: '#FFB800',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '7',
      userId: '1',
      name: 'Atorvastatina',
      dosage: '40',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-07-01'),
      notes: 'Tomar à noite',
      colorCode: '#3B82F6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '8',
      userId: '1',
      name: 'Levotiroxina',
      dosage: '50',
      dosageUnit: 'mcg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-08-01'),
      notes: 'Em jejum, 30-60min antes do café',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '9',
      userId: '1',
      name: 'Ácido Acetilsalicílico',
      dosage: '100',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-02-01'),
      notes: 'Após o jantar',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '10',
      userId: '1',
      name: 'Atenolol',
      dosage: '25',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-04-01'),
      notes: 'Controle de frequência cardíaca',
      colorCode: '#3B82F6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '11',
      userId: '1',
      name: 'Captopril',
      dosage: '25',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '8/8h',
      startDate: new Date('2024-05-01'),
      notes: 'Tomar em caso de pressão alta',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '12',
      userId: '1',
      name: 'Dipirona',
      dosage: '500',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: 'SOS',
      startDate: new Date('2024-12-01'),
      notes: 'Apenas em caso de dor ou febre',
      colorCode: '#F59E0B',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '13',
      userId: '1',
      name: 'Vitamina D3',
      dosage: '7000',
      dosageUnit: 'unit',
      form: 'capsule',
      frequency: '168/168h',
      startDate: new Date('2024-01-01'),
      notes: 'Uma vez por semana',
      colorCode: '#FFB800',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '14',
      userId: '1',
      name: 'Ômega 3',
      dosage: '1000',
      dosageUnit: 'mg',
      form: 'capsule',
      frequency: '24/24h',
      startDate: new Date('2024-01-01'),
      notes: 'Durante o almoço',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '15',
      userId: '1',
      name: 'Metoprolol',
      dosage: '100',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-07-01'),
      notes: 'Controle de arritmia',
      colorCode: '#7B5FFF',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '16',
      userId: '1',
      name: 'Enalapril',
      dosage: '10',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-08-01'),
      notes: 'Anti-hipertensivo',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '17',
      userId: '1',
      name: 'Hidroclorotiazida',
      dosage: '25',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-09-01'),
      notes: 'Tomar pela manhã',
      colorCode: '#3B82F6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '18',
      userId: '1',
      name: 'Prednisona',
      dosage: '20',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-11-15'),
      endDate: new Date('2024-12-15'),
      notes: 'Desmame gradual',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '19',
      userId: '1',
      name: 'Azitromicina',
      dosage: '500',
      dosageUnit: 'mg',
      form: 'capsule',
      frequency: '24/24h',
      startDate: new Date('2024-12-01'),
      endDate: new Date('2024-12-05'),
      notes: 'Antibiótico - 5 dias',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '20',
      userId: '1',
      name: 'Clonazepam',
      dosage: '2',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-06-01'),
      notes: 'Tomar antes de dormir',
      colorCode: '#7B5FFF',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '21',
      userId: '1',
      name: 'Fluoxetina',
      dosage: '20',
      dosageUnit: 'mg',
      form: 'capsule',
      frequency: '24/24h',
      startDate: new Date('2024-05-01'),
      notes: 'Pela manhã, com ou sem alimento',
      colorCode: '#FF6B9D',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '22',
      userId: '1',
      name: 'Sertralina',
      dosage: '50',
      dosageUnit: 'mg',
      form: 'capsule',
      frequency: '24/24h',
      startDate: new Date('2024-10-01'),
      notes: 'Antidepressivo',
      colorCode: '#7B5FFF',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '23',
      userId: '1',
      name: 'Bromazepam',
      dosage: '3',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-11-01'),
      notes: 'Ansiolítico',
      colorCode: '#FF6B9D',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '24',
      userId: '1',
      name: 'Ranitidina',
      dosage: '150',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-08-15'),
      notes: 'Protetor gástrico',
      colorCode: '#FFB800',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '25',
      userId: '1',
      name: 'Dexametasona',
      dosage: '4',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '12/12h',
      startDate: new Date('2024-11-20'),
      endDate: new Date('2024-12-10'),
      notes: 'Anti-inflamatório corticoide',
      colorCode: '#EF4444',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '26',
      userId: '1',
      name: 'Cetirizina',
      dosage: '10',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-09-01'),
      notes: 'Antialérgico',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '27',
      userId: '1',
      name: 'Gliclazida',
      dosage: '30',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-07-01'),
      notes: 'Controle glicêmico - antes do café',
      colorCode: '#3B82F6',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '28',
      userId: '1',
      name: 'Cálcio + Vitamina D',
      dosage: '600',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-01-01'),
      notes: 'Saúde óssea',
      colorCode: '#FFB800',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '29',
      userId: '1',
      name: 'Ácido Fólico',
      dosage: '5',
      dosageUnit: 'mg',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-04-01'),
      notes: 'Suplementação',
      colorCode: '#10B981',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '30',
      userId: '1',
      name: 'Complexo B',
      dosage: '1',
      dosageUnit: 'tablet',
      form: 'tablet',
      frequency: '24/24h',
      startDate: new Date('2024-02-01'),
      notes: 'Vitaminas do complexo B',
      colorCode: '#FFB800',
      icon: 'pill',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  async getAll(): Promise<Medication[]> {
    // Simular delay de rede
    await new Promise(resolve => setTimeout(resolve, 300));
    return [...this.medications];
  }

  async getById(id: string): Promise<Medication | null> {
    await new Promise(resolve => setTimeout(resolve, 200));
    return this.medications.find(med => med.id === id) ?? null;
  }

  async save(medication: Medication): Promise<void> {
    await new Promise(resolve => setTimeout(resolve, 300));
    this.medications.push(medication);
  }

  async update(id: string, updates: Partial<Medication>): Promise<void> {
    await new Promise(resolve => setTimeout(resolve, 300));
    const index = this.medications.findIndex(med => med.id === id);

    if (index === -1) {
      throw new Error(`Medication with id ${id} not found`);
    }

    this.medications[index] = {
      ...this.medications[index],
      ...updates,
      id,
    } as Medication;
  }

  async delete(id: string): Promise<void> {
    await new Promise(resolve => setTimeout(resolve, 300));
    this.medications = this.medications.filter(med => med.id !== id);
  }
}
